version: "3"

services:
  torproxy:
    image: ghcr.io/guest42069/torproxy:latest # https://github.com/guest42069/tortainer
    restart: unless-stopped
    volumes:
      - type: volume
        source: var-lib-tor
        target: /var/lib/tor
    networks:
      pihole_net:
        ipv4_address: 10.69.0.4

  dohproxy:
    image: ghcr.io/guest42069/dohproxy:latest
    restart: unless-stopped
#    volumes:
#      - "./dnscrypt-proxy/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    networks:
      pihole_net:
        ipv4_address: 10.69.0.2
    depends_on:
      - torproxy

  pihole:
    image: pihole/pihole
    restart: unless-stopped
    volumes:
      - type: volume
        source: etc-dnsmasqd
        target: /etc/dnsmasq.d/
      - type: volume
        source: etc-pihole
        target: /etc/pihole/
#    ports:
#      - "YOUR_LAN_IP_HERE:80:80/tcp"
#      - "YOUR_LAN_IP_HERE:53:53/tcp"
#      - "YOUR_LAN_IP_HERE:53:53/udp"
    environment:
      - ServerIP=10.69.0.3
      - PIHOLE_DNS_=10.69.0.2#5054
      - TZ=Europe/London
    networks:
      pihole_net:
        ipv4_address: 10.69.0.3
    dns:
      - 127.0.0.1
    depends_on:
      - dohproxy

networks:
  pihole_net:
    ipam:
      config:
      - subnet: 10.69.0.0/29

volumes:
  etc-dnsmasqd:
  etc-pihole:
  var-lib-tor:
